baseURL = 'https://mrpointing.com/'
languageCode = 'en-us'
title = 'mr.pointing'
theme = ['hugo-embed-pdf-shortcode', 'mr-p-hello-friend-ng']
enableInlineShortcodes = true
paginate     = 10
author = "Richard Pointing"
copyright = "[CC BY-NC-ND](https://creativecommons.org/licenses/by-nc-nd/4.0/)"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  homeSubtitle = "Computer Science Teacher"
  disableReadOtherPosts = false
  enableSharingButtons = false
  enableGlobalLanguageMenu = false
  description = "Mr. Pointing - Computer Science Teacher"
  keywords = "homepage, blog"
  images = [""]
  
  

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Mr. Pointing"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    
  [languages.en.params]
    subtitle  = "Computer Science Teacher"
    
	[languages.en.params.logo]
      logoText = "mr. pointing"
      logoHomeLink = "/"

[menu]
	[[menu.main]]
	  identifier = "blog"
	  name       = "Posts"
	  url        = "/posts"
		
	[[menu.main]]
	  identifier = "about"
	  name       = "About"
	  url        = "/about"
	  
	[[menu.main]]
	  identifier = "projects"
	  name       = "Projects"
	  url        = "/projects"
	
	[[menu.main]]
	  identifier = "notes"
	  name       = "Notes"
	  url        = "/notes"
	  
	[[menu.main]]
	  identifier = "now"
	  name       = "Now"
	  url        = "/now"